version: '3.8'

services:
  app:
    container_name: goalwith-app
    build: .
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/goal_with?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1215
    depends_on:
      - db
    restart: always

  db:
    container_name: goalwith-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: goal_with
      MYSQL_ROOT_PASSWORD: 1215
    volumes:
      # 호스트의 ./db-data 폴더와 컨테이너의 데이터 폴더를 연결 (데이터 보존용)
      - ./db-data:/var/lib/mysql
    command:
      # 한글 저장을 위한 문자셋 설정
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always